
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Principal;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int METODO = 3;
  public static final int error = 1;
  public static final int P = 5;
  public static final int PROPIEDADES = 2;
  public static final int EOF = 0;
  public static final int CLASE = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROPIEDADES",
  "METODO",
  "CLASE",
  "P"
  };
}

